Site Integration MOD v1.0
[INSERT]
CONFIG_NEW
(C_VARIABLE,C_VALUE)#('STRSITEHEADER','0')
(C_VARIABLE,C_VALUE)#('STRSITELEFT','0')
(C_VARIABLE,C_VALUE)#('STRSITERIGHT','0')
(C_VARIABLE,C_VALUE)#('STRSITEFOOTER','0')
(C_VARIABLE,C_VALUE)#('STRSITEINTEGENABLED','0')
(C_VARIABLE,C_VALUE)#('STRSITEBORDER','0')
[END]